# Generated by Django 3.1.2 on 2020-12-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201205_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, related_name='biddedListing', to='auctions.listing'),
        ),
    ]
